# Generated by Django 3.0.5 on 2020-05-04 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200503_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safaty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
