# Generated by Django 3.0.5 on 2020-05-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_safaty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Safaty',
        ),
    ]
