# Generated by Django 3.0.5 on 2020-05-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_delete_safaty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
