# Generated by Django 3.0.5 on 2020-05-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20200508_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(max_length=100, verbose_name='Телеграм канал')),
            ],
            options={
                'verbose_name': 'Телеграм канал',
                'verbose_name_plural': 'Телеграм каналы',
            },
        ),
    ]
