# Generated by Django 3.0.5 on 2020-05-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_telegramchannel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramchannel',
            old_name='name',
            new_name='link',
        ),
    ]
