# Generated by Django 3.0.5 on 2020-05-08 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20200508_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='link',
            field=models.URLField(max_length=100, validators=[django.core.validators.URLValidator()], verbose_name='Телеграм канал'),
        ),
    ]
