# Generated by Django 3.0.6 on 2020-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20200508_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='movies.Actor', verbose_name='актеры'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='link',
            field=models.URLField(max_length=100, verbose_name='Телеграм канал'),
        ),
    ]
