# Generated by Django 3.0.6 on 2020-05-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20200520_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='telegram',
            field=models.URLField(max_length=100, verbose_name='Telegram'),
        ),
    ]
