# Generated by Django 3.0.6 on 2020-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20200526_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='short_title',
            field=models.CharField(blank=True, help_text='для фильмов которые делятся на части', max_length=100, verbose_name='Короткое название'),
        ),
    ]
