# Generated by Django 3.0.6 on 2020-06-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movie_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='wikipedia',
            field=models.URLField(blank=True, max_length=100, verbose_name='Wikipedia'),
        ),
    ]
