# Generated by Django 3.0.6 on 2020-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20200606_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='online',
            field=models.URLField(blank=True, max_length=160, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='movie',
            name='online_de',
            field=models.URLField(blank=True, max_length=160, null=True, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='movie',
            name='online_en',
            field=models.URLField(blank=True, max_length=160, null=True, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='movie',
            name='online_ru',
            field=models.URLField(blank=True, max_length=160, null=True, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='movie',
            name='wallpaper',
            field=models.ImageField(blank=True, upload_to='wallpapers/', verbose_name='Обложка'),
        ),
    ]
