# Generated by Django 3.0.6 on 2020-06-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_auto_20200608_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='wikipedia_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='director',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='director',
            name='wikipedia_ar',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='online_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='short_title_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='telegram_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='wall_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='wikipedia_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere_ar',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='youtube_ar',
        ),
    ]
