# Generated by Django 3.0.6 on 2020-06-09 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_auto_20200608_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='actor',
            name='wikipedia_fr',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Википедия'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='director',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='director',
            name='wikipedia_fr',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Википедия'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='online_fr',
            field=models.URLField(blank=True, max_length=160, null=True, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_fr',
            field=models.ImageField(null=True, upload_to='movies/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='movie',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='для фильмов которые делятся на части', max_length=100, null=True, verbose_name='Короткое название'),
        ),
        migrations.AddField(
            model_name='movie',
            name='telegram_fr',
            field=models.URLField(max_length=100, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='movie',
            name='wall_fr',
            field=models.BooleanField(default=False, verbose_name='Главная страница'),
        ),
        migrations.AddField(
            model_name='movie',
            name='wikipedia_fr',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Wikipedia'),
        ),
        migrations.AddField(
            model_name='movie',
            name='world_premiere_fr',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Премьера'),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_fr',
            field=models.URLField(help_text='https://www.youtube.com/embed/', max_length=100, null=True, verbose_name='Youtube'),
        ),
    ]
