# Generated by Django 3.0.6 on 2020-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=130, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_ar',
            field=models.CharField(max_length=130, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_de',
            field=models.CharField(max_length=130, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_en',
            field=models.CharField(max_length=130, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_fr',
            field=models.CharField(max_length=130, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_ru',
            field=models.CharField(max_length=130, null=True, verbose_name='Страна'),
        ),
    ]
