# Generated by Django 3.0.6 on 2020-07-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_auto_20200704_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
