# Generated by Django 3.0.6 on 2020-07-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_auto_20200716_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
