# Generated by Django 3.0.6 on 2020-07-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_auto_20200718_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(default=10, max_length=10, verbose_name='imdb'),
        ),
    ]
