# Generated by Django 3.0.6 on 2020-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_movie_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Background'),
        ),
    ]
