# Generated by Django 3.0.6 on 2020-12-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_movie_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='visit_num',
            field=models.PositiveIntegerField(default=1, verbose_name='Популярность'),
        ),
    ]
